In [1]:
my_list =[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Build in methods

Arange

Return evenly spaced values within a given interval.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# Zeros and Ones

Generate Arrays zeros and ones

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace
Return evenly spaced numbers over a specified interval.

In [29]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [30]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# EYE

Creates an identity matrix

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random

Numpy also has lots of ways to create random number arrays:

rand

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [35]:
np.random.rand(2)

array([0.84186848, 0.96277154])

In [36]:
np.random.rand(5,5)

array([[0.50124611, 0.35952444, 0.80911593, 0.68636756, 0.62286052],
       [0.91339995, 0.22507237, 0.38221807, 0.48832642, 0.33789826],
       [0.51396598, 0.29512379, 0.56261759, 0.38132234, 0.25646637],
       [0.49954763, 0.34722702, 0.01268987, 0.16001238, 0.94519723],
       [0.32736727, 0.89365916, 0.7926581 , 0.70629321, 0.03872578]])

randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

In [37]:
np.random.randn(2)

array([-0.12968677, -1.55506531])

In [38]:
np.random.randn(5,5)

array([[-1.78388349, -0.01550736, -0.14494492,  0.34833781,  0.29489564],
       [-0.21974739,  0.60227012, -1.04698679, -0.88744519, -0.17220865],
       [ 0.32221528,  0.86857722,  0.97136557, -1.16766283, -0.82385338],
       [ 0.26135291,  0.73769856,  1.77733791,  1.44510334, -0.60861706],
       [ 0.51280237,  0.68489192, -0.31181432, -0.7397275 , -0.4259598 ]])

randint

Return random integers from low (inclusive) to high (exclusive).

In [39]:
np.random.randint(1,100)

76

In [40]:
np.random.randint(1,100,10)

array([82, 85, 65, 69, 17, 52, 24, 77, 81, 24])

In [41]:
arr = np.arange(25)

In [44]:
ranarr =np.random.randint(0,50,10)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
ranarr

array([32, 24, 16, 18, 23, 48, 44, 24, 13,  0])

# Reshape

Returns an array containing the same data with a new shape.

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [48]:
ranarr

array([32, 24, 16, 18, 23, 48, 44, 24, 13,  0])

In [49]:
ranarr.max()

48

In [50]:
ranarr.min()

0

In [51]:
ranarr.argmin()

9

# Shape

Shape is an attribute that arrays have (not a method):

In [52]:
arr.shape

(25,)

In [57]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [58]:
arr.reshape(25,1).shape

(25, 1)

# datatype

You can also grab the data type of the object in the array:

In [59]:
arr.dtype

dtype('int32')